(
 ;; '("quickdocs" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/")
 ;; '("wiki" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
 ;; '("define" "https://en.wiktionary.org/w/index.php?search=~a" "https://en.wiktionary.org/")
 ;; '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
 ;; '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")

 ("gg" "https://www.google.com/search?q=~a" "https://www.google.com/")
 ("nd" "https://en.dict.naver.com/#/search?query=~a" "https://en.dict.naver.com/#/main")
 ("gk" "https://translate.google.co.kr/?hl=ko&sl=auto&tl=ko&text=~a&op=translate" "https://translate.google.co.kr/?hl=ko&sl=auto&tl=ko&text=&op=translate")
 ("ge" "https://translate.google.co.kr/?hl=ko&sl=auto&tl=en&text=~a&op=translate" "https://translate.google.co.kr/?hl=ko&sl=auto&tl=en&text=&op=translate")
 ("er" "https://www.reddit.com/r/emacs/search/?q=~a&restrict_sr=1&sr_nsfw=" "https://www.reddit.com/r/emacs/")
 ("dblp" "https://dblp.org/search?q=~a" "https://dblp.uni-trier.de/")
 ("arxiv" "https://arxiv.org/search/?query=~a&searchtype=all&abstracts=show&order=-announced_date_first" "https://arxiv.org/")
 ("scholar" "https://scholar.google.com/scholar?hl=ko&as_sdt=0%2C5&q=~a&btnG=" "https://scholar.google.com/")
 ;; ("gs" "https://scholar.google.com/scholar?hl=ko&as_sdt=0%2C5&q=~a&btnG=" "https://scholar.google.com/")
 ("gm" "https://mail.google.com/mail/u/0/#search/~a" "https://mail.google.com/mail/u/0/#inbox")
 ("github" "https://github.com/daehwannam/~a" "https://github.com/daehwannam?tab=repositories")
 ("ctan" "https://www.ctan.org/search?phrase=~a" "https://www.ctan.org/")
 ("reddit-emacs" "https://www.reddit.com/r/emacs/search/?q=~a&restrict_sr=1&sr_nsfw=" "https://www.reddit.com/r/emacs/")
 )
